### ISSUE TITLE
Change in figure for abstract model

### ISSUE THREAD

**Issue by agbeltran** [ISA-tools/isa-specs#1]
To be consistent with the terminology, let's change 'ontology reference' to 'ontology source' (or explain in the text their relationship) in the concept map at http://isa-specs.readthedocs.io/en/latest/isamodel.html
Also check if other changes are required.

**Comment by djcomlab** [comment]
There's also a spelling mistake: "hardward" -> "hardware" by `protocol component`

**Comment by djcomlab** [comment]
Fixed in cdba7e93441b9d32dbbc83bffdfe029221dce483, closing.

**Comment by agbeltran** [comment]
Actually, I don't think this is fixed, as the figure refers to "ontology reference" and that's not explained in the text at all.

**Comment by djcomlab** [comment]
Added text to explain "ontology reference".

**Comment by djcomlab** [comment]
Now explained in text in textbox below the diagram, closing.
