### ISSUE TITLE
Change order of presentation in the ISA model doc

### ISSUE THREAD

**Issue by agbeltran** [ISA-tools/isa-specs#5]
Currently, the documentation for the model starts with Ontology Annotation/Ontology Source/Unit/Publication.

Change the order so that the main elements (Investigation/Study/Assay) are described first and the other elements are introduced in relation to the main elements (e.g. Publications for both Investigation and Study).

**Comment by djcomlab** [comment]
I can see the order has been changed. Are these changes all that are needed?

**Comment by agbeltran** [comment]
yes, I think it should be complete. Thanks
